<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Delete_Instructor.aspx.cs" Inherits="aspday2.Delete_Instructor" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table style="width: 100%">
        <tr>
            <td style="height: 17px">&nbsp;</td>
            <td style="height: 17px">
                Add Instructor:</td>
            <td style="height: 17px"></td>
        </tr>
        <tr>
            <td>Instructor Name:</td>
            <td>
                <asp:TextBox ID="txt_nameadd" runat="server"></asp:TextBox>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Instructor Age:</td>
            <td>
                <asp:TextBox ID="txt_ageadd" runat="server"></asp:TextBox>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Instructor E-Mail:</td>
            <td>
                <asp:TextBox ID="txt_emailadd" runat="server"></asp:TextBox>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Instructor Gender:</td>
            <td>
                <asp:RadioButtonList ID="rbl_genderadd" runat="server" RepeatDirection="Horizontal">
                    <asp:ListItem>Male</asp:ListItem>
                    <asp:ListItem>Female</asp:ListItem>
                </asp:RadioButtonList>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Department:</td>
            <td>
                <asp:DropDownList ID="ddl_deptadd" runat="server">
                </asp:DropDownList>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Add Instructor" />
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                View Instructors in a spcefic Department:
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Department:</td>
            <td>
                <asp:DropDownList ID="ddl_inst" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddl_inst_SelectedIndexChanged">
                </asp:DropDownList>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Info:</td>
            <td>
                <asp:GridView ID="gv_inst" runat="server" AutoGenerateDeleteButton="True" DataKeyNames="Inst_ID" OnRowDeleting="gv_inst_RowDeleting" OnSelectedIndexChanged="gv_inst_SelectedIndexChanged">
                </asp:GridView>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>Delete Instructor:</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Department:<asp:DropDownList ID="ddl_deptdel" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddl_deptdel_SelectedIndexChanged">
                </asp:DropDownList>
            </td>
            <td>Instructor:<asp:DropDownList ID="ddl_instdel" runat="server">
                </asp:DropDownList>
            </td>
            <td>
                <asp:Button ID="btn_del" runat="server" OnClick="btn_del_Click" Text="Delete" />
            </td>
        </tr>
    </table>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
</asp:Content>
